// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/station.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PollStationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollStationRequest) Reset() {
	*x = PollStationRequest{}
	mi := &file_proto_station_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollStationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollStationRequest) ProtoMessage() {}

func (x *PollStationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_station_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollStationRequest.ProtoReflect.Descriptor instead.
func (*PollStationRequest) Descriptor() ([]byte, []int) {
	return file_proto_station_proto_rawDescGZIP(), []int{0}
}

func (x *PollStationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type NearStationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CarLatitude   float64                `protobuf:"fixed64,1,opt,name=car_latitude,json=carLatitude,proto3" json:"car_latitude,omitempty"`
	CarLongitude  float64                `protobuf:"fixed64,2,opt,name=car_longitude,json=carLongitude,proto3" json:"car_longitude,omitempty"`
	SearchRadius  int64                  `protobuf:"varint,3,opt,name=search_radius,json=searchRadius,proto3" json:"search_radius,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NearStationRequest) Reset() {
	*x = NearStationRequest{}
	mi := &file_proto_station_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NearStationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NearStationRequest) ProtoMessage() {}

func (x *NearStationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_station_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NearStationRequest.ProtoReflect.Descriptor instead.
func (*NearStationRequest) Descriptor() ([]byte, []int) {
	return file_proto_station_proto_rawDescGZIP(), []int{1}
}

func (x *NearStationRequest) GetCarLatitude() float64 {
	if x != nil {
		return x.CarLatitude
	}
	return 0
}

func (x *NearStationRequest) GetCarLongitude() float64 {
	if x != nil {
		return x.CarLongitude
	}
	return 0
}

func (x *NearStationRequest) GetSearchRadius() int64 {
	if x != nil {
		return x.SearchRadius
	}
	return 0
}

type UpdateStationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StationName   string                 `protobuf:"bytes,1,opt,name=station_name,json=stationName,proto3" json:"station_name,omitempty"`
	StockIncr     int64                  `protobuf:"varint,2,opt,name=stock_incr,json=stockIncr,proto3" json:"stock_incr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStationRequest) Reset() {
	*x = UpdateStationRequest{}
	mi := &file_proto_station_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStationRequest) ProtoMessage() {}

func (x *UpdateStationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_station_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStationRequest.ProtoReflect.Descriptor instead.
func (*UpdateStationRequest) Descriptor() ([]byte, []int) {
	return file_proto_station_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateStationRequest) GetStationName() string {
	if x != nil {
		return x.StationName
	}
	return ""
}

func (x *UpdateStationRequest) GetStockIncr() int64 {
	if x != nil {
		return x.StockIncr
	}
	return 0
}

type StationReply struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Stock            int64                  `protobuf:"varint,1,opt,name=stock,proto3" json:"stock,omitempty"`
	StationLatitude  float64                `protobuf:"fixed64,2,opt,name=station_latitude,json=stationLatitude,proto3" json:"station_latitude,omitempty"`
	StationLongitude float64                `protobuf:"fixed64,3,opt,name=station_longitude,json=stationLongitude,proto3" json:"station_longitude,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StationReply) Reset() {
	*x = StationReply{}
	mi := &file_proto_station_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StationReply) ProtoMessage() {}

func (x *StationReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_station_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StationReply.ProtoReflect.Descriptor instead.
func (*StationReply) Descriptor() ([]byte, []int) {
	return file_proto_station_proto_rawDescGZIP(), []int{3}
}

func (x *StationReply) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *StationReply) GetStationLatitude() float64 {
	if x != nil {
		return x.StationLatitude
	}
	return 0
}

func (x *StationReply) GetStationLongitude() float64 {
	if x != nil {
		return x.StationLongitude
	}
	return 0
}

type UpdateStationReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updated       bool                   `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStationReply) Reset() {
	*x = UpdateStationReply{}
	mi := &file_proto_station_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStationReply) ProtoMessage() {}

func (x *UpdateStationReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_station_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStationReply.ProtoReflect.Descriptor instead.
func (*UpdateStationReply) Descriptor() ([]byte, []int) {
	return file_proto_station_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateStationReply) GetUpdated() bool {
	if x != nil {
		return x.Updated
	}
	return false
}

var File_proto_station_proto protoreflect.FileDescriptor

const file_proto_station_proto_rawDesc = "" +
	"\n" +
	"\x13proto/station.proto\x12\astation\"(\n" +
	"\x12PollStationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x81\x01\n" +
	"\x12NearStationRequest\x12!\n" +
	"\fcar_latitude\x18\x01 \x01(\x01R\vcarLatitude\x12#\n" +
	"\rcar_longitude\x18\x02 \x01(\x01R\fcarLongitude\x12#\n" +
	"\rsearch_radius\x18\x03 \x01(\x03R\fsearchRadius\"X\n" +
	"\x14UpdateStationRequest\x12!\n" +
	"\fstation_name\x18\x01 \x01(\tR\vstationName\x12\x1d\n" +
	"\n" +
	"stock_incr\x18\x02 \x01(\x03R\tstockIncr\"|\n" +
	"\fStationReply\x12\x14\n" +
	"\x05stock\x18\x01 \x01(\x03R\x05stock\x12)\n" +
	"\x10station_latitude\x18\x02 \x01(\x01R\x0fstationLatitude\x12+\n" +
	"\x11station_longitude\x18\x03 \x01(\x01R\x10stationLongitude\".\n" +
	"\x12UpdateStationReply\x12\x18\n" +
	"\aupdated\x18\x01 \x01(\bR\aupdated2\xdc\x01\n" +
	"\aStation\x12A\n" +
	"\vPollStation\x12\x1b.station.PollStationRequest\x1a\x15.station.StationReply\x12A\n" +
	"\vFindNearest\x12\x1b.station.NearStationRequest\x1a\x15.station.StationReply\x12K\n" +
	"\rUpdateStation\x12\x1d.station.UpdateStationRequest\x1a\x1b.station.UpdateStationReplyB)Z'github.com/psamuthis/grpc-station/protob\x06proto3"

var (
	file_proto_station_proto_rawDescOnce sync.Once
	file_proto_station_proto_rawDescData []byte
)

func file_proto_station_proto_rawDescGZIP() []byte {
	file_proto_station_proto_rawDescOnce.Do(func() {
		file_proto_station_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_station_proto_rawDesc), len(file_proto_station_proto_rawDesc)))
	})
	return file_proto_station_proto_rawDescData
}

var file_proto_station_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_station_proto_goTypes = []any{
	(*PollStationRequest)(nil),   // 0: station.PollStationRequest
	(*NearStationRequest)(nil),   // 1: station.NearStationRequest
	(*UpdateStationRequest)(nil), // 2: station.UpdateStationRequest
	(*StationReply)(nil),         // 3: station.StationReply
	(*UpdateStationReply)(nil),   // 4: station.UpdateStationReply
}
var file_proto_station_proto_depIdxs = []int32{
	0, // 0: station.Station.PollStation:input_type -> station.PollStationRequest
	1, // 1: station.Station.FindNearest:input_type -> station.NearStationRequest
	2, // 2: station.Station.UpdateStation:input_type -> station.UpdateStationRequest
	3, // 3: station.Station.PollStation:output_type -> station.StationReply
	3, // 4: station.Station.FindNearest:output_type -> station.StationReply
	4, // 5: station.Station.UpdateStation:output_type -> station.UpdateStationReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_station_proto_init() }
func file_proto_station_proto_init() {
	if File_proto_station_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_station_proto_rawDesc), len(file_proto_station_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_station_proto_goTypes,
		DependencyIndexes: file_proto_station_proto_depIdxs,
		MessageInfos:      file_proto_station_proto_msgTypes,
	}.Build()
	File_proto_station_proto = out.File
	file_proto_station_proto_goTypes = nil
	file_proto_station_proto_depIdxs = nil
}
