// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.0
// source: proto/station.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Station_PollStation_FullMethodName   = "/station.Station/PollStation"
	Station_FindNearest_FullMethodName   = "/station.Station/FindNearest"
	Station_UpdateStation_FullMethodName = "/station.Station/UpdateStation"
)

// StationClient is the client API for Station service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StationClient interface {
	PollStation(ctx context.Context, in *PollStationRequest, opts ...grpc.CallOption) (*StationReply, error)
	FindNearest(ctx context.Context, in *NearStationRequest, opts ...grpc.CallOption) (*StationReply, error)
	UpdateStation(ctx context.Context, in *UpdateStationRequest, opts ...grpc.CallOption) (*UpdateStationReply, error)
}

type stationClient struct {
	cc grpc.ClientConnInterface
}

func NewStationClient(cc grpc.ClientConnInterface) StationClient {
	return &stationClient{cc}
}

func (c *stationClient) PollStation(ctx context.Context, in *PollStationRequest, opts ...grpc.CallOption) (*StationReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StationReply)
	err := c.cc.Invoke(ctx, Station_PollStation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stationClient) FindNearest(ctx context.Context, in *NearStationRequest, opts ...grpc.CallOption) (*StationReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StationReply)
	err := c.cc.Invoke(ctx, Station_FindNearest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stationClient) UpdateStation(ctx context.Context, in *UpdateStationRequest, opts ...grpc.CallOption) (*UpdateStationReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateStationReply)
	err := c.cc.Invoke(ctx, Station_UpdateStation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StationServer is the server API for Station service.
// All implementations must embed UnimplementedStationServer
// for forward compatibility.
type StationServer interface {
	PollStation(context.Context, *PollStationRequest) (*StationReply, error)
	FindNearest(context.Context, *NearStationRequest) (*StationReply, error)
	UpdateStation(context.Context, *UpdateStationRequest) (*UpdateStationReply, error)
	mustEmbedUnimplementedStationServer()
}

// UnimplementedStationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStationServer struct{}

func (UnimplementedStationServer) PollStation(context.Context, *PollStationRequest) (*StationReply, error) {
	return nil, status.Error(codes.Unimplemented, "method PollStation not implemented")
}
func (UnimplementedStationServer) FindNearest(context.Context, *NearStationRequest) (*StationReply, error) {
	return nil, status.Error(codes.Unimplemented, "method FindNearest not implemented")
}
func (UnimplementedStationServer) UpdateStation(context.Context, *UpdateStationRequest) (*UpdateStationReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateStation not implemented")
}
func (UnimplementedStationServer) mustEmbedUnimplementedStationServer() {}
func (UnimplementedStationServer) testEmbeddedByValue()                 {}

// UnsafeStationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StationServer will
// result in compilation errors.
type UnsafeStationServer interface {
	mustEmbedUnimplementedStationServer()
}

func RegisterStationServer(s grpc.ServiceRegistrar, srv StationServer) {
	// If the following call panics, it indicates UnimplementedStationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Station_ServiceDesc, srv)
}

func _Station_PollStation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PollStationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StationServer).PollStation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Station_PollStation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StationServer).PollStation(ctx, req.(*PollStationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Station_FindNearest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NearStationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StationServer).FindNearest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Station_FindNearest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StationServer).FindNearest(ctx, req.(*NearStationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Station_UpdateStation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StationServer).UpdateStation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Station_UpdateStation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StationServer).UpdateStation(ctx, req.(*UpdateStationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Station_ServiceDesc is the grpc.ServiceDesc for Station service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Station_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "station.Station",
	HandlerType: (*StationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PollStation",
			Handler:    _Station_PollStation_Handler,
		},
		{
			MethodName: "FindNearest",
			Handler:    _Station_FindNearest_Handler,
		},
		{
			MethodName: "UpdateStation",
			Handler:    _Station_UpdateStation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/station.proto",
}
